import { DeckId, type Card } from './types.js';

/**
 * Each deck has 50 cards; a room draws 25 at random from its chosen deck for the actual
 * board (see Room.ts). Illustrations are never real photos/posters/box art/logos — the
 * client renders a hand-chosen generated portrait per card id (see components/Room's
 * Avatar/AnimalAvatar/MediaAvatar + their `*Designs.ts` lookup tables). That's what keeps
 * real names and titles (Celebrities/Movies/VideoGames) safe to use here: we never
 * reproduce anyone's actual likeness or any studio's artwork, only text.
 */

const FICTIONAL: Card[] = [
  { id: 'fictional-01', displayName: 'Алекс Нова' },
  { id: 'fictional-02', displayName: 'Марина Вейл' },
  { id: 'fictional-03', displayName: 'Дени Лорк' },
  { id: 'fictional-04', displayName: 'Соня Брайт' },
  { id: 'fictional-05', displayName: 'Тимур Аксель' },
  { id: 'fictional-06', displayName: 'Ирен Фальк' },
  { id: 'fictional-07', displayName: 'Глеб Орсо' },
  { id: 'fictional-08', displayName: 'Ясна Рицци' },
  { id: 'fictional-09', displayName: 'Марк Силва' },
  { id: 'fictional-10', displayName: 'Лия Дорн' },
  { id: 'fictional-11', displayName: 'Виктор Эш' },
  { id: 'fictional-12', displayName: 'Ника Рейн' },
  { id: 'fictional-13', displayName: 'Савва Крон' },
  { id: 'fictional-14', displayName: 'Эмма Квест' },
  { id: 'fictional-15', displayName: 'Данте Моро' },
  { id: 'fictional-16', displayName: 'Агата Лунд' },
  { id: 'fictional-17', displayName: 'Рубен Стам' },
  { id: 'fictional-18', displayName: 'Вера Остин' },
  { id: 'fictional-19', displayName: 'Леон Фарбер' },
  { id: 'fictional-20', displayName: 'Клара Веско' },
  { id: 'fictional-21', displayName: 'Игорь Блэйз' },
  { id: 'fictional-22', displayName: 'Милана Соль' },
  { id: 'fictional-23', displayName: 'Фёдор Айс' },
  { id: 'fictional-24', displayName: 'Таня Норд' },
  { id: 'fictional-25', displayName: 'Оскар Рейв' },
  { id: 'fictional-26', displayName: 'Эрик Солт' },
  { id: 'fictional-27', displayName: 'Нина Фрост' },
  { id: 'fictional-28', displayName: 'Бруно Тейл' },
  { id: 'fictional-29', displayName: 'Сельма Крафт' },
  { id: 'fictional-30', displayName: 'Отто Брим' },
  { id: 'fictional-31', displayName: 'Ида Варн' },
  { id: 'fictional-32', displayName: 'Ральф Дюна' },
  { id: 'fictional-33', displayName: 'Майя Стерн' },
  { id: 'fictional-34', displayName: 'Густав Лин' },
  { id: 'fictional-35', displayName: 'Флёр Ами' },
  { id: 'fictional-36', displayName: 'Зено Карт' },
  { id: 'fictional-37', displayName: 'Роза Виль' },
  { id: 'fictional-38', displayName: 'Феликс Орн' },
  { id: 'fictional-39', displayName: 'Джина Хейл' },
  { id: 'fictional-40', displayName: 'Космо Рид' },
  { id: 'fictional-41', displayName: 'Лара Финч' },
  { id: 'fictional-42', displayName: 'Артур Клэй' },
  { id: 'fictional-43', displayName: 'Белла Сорн' },
  { id: 'fictional-44', displayName: 'Ивар Шторм' },
  { id: 'fictional-45', displayName: 'Мона Квилл' },
  { id: 'fictional-46', displayName: 'Дрейк Эллис' },
  { id: 'fictional-47', displayName: 'Сара Нокс' },
  { id: 'fictional-48', displayName: 'Тео Брант' },
  { id: 'fictional-49', displayName: 'Вики Сейл' },
  { id: 'fictional-50', displayName: 'Хьюго Дрейк' },
];

// Long-deceased historical figures only — no living-person likeness/publicity concerns,
// and we draw a generated face, never a real portrait, so there's no photo to clear either.
const CELEBRITIES: Card[] = [
  { id: 'celebrity-01', displayName: 'Альберт Эйнштейн' },
  { id: 'celebrity-02', displayName: 'Леонардо да Винчи' },
  { id: 'celebrity-03', displayName: 'Исаак Ньютон' },
  { id: 'celebrity-04', displayName: 'Мария Кюри' },
  { id: 'celebrity-05', displayName: 'Чарльз Дарвин' },
  { id: 'celebrity-06', displayName: 'Никола Тесла' },
  { id: 'celebrity-07', displayName: 'Вольфганг Амадей Моцарт' },
  { id: 'celebrity-08', displayName: 'Людвиг ван Бетховен' },
  { id: 'celebrity-09', displayName: 'Уильям Шекспир' },
  { id: 'celebrity-10', displayName: 'Александр Пушкин' },
  { id: 'celebrity-11', displayName: 'Клеопатра' },
  { id: 'celebrity-12', displayName: 'Юлий Цезарь' },
  { id: 'celebrity-13', displayName: 'Жанна д’Арк' },
  { id: 'celebrity-14', displayName: 'Христофор Колумб' },
  { id: 'celebrity-15', displayName: 'Галилео Галилей' },
  { id: 'celebrity-16', displayName: 'Чарли Чаплин' },
  { id: 'celebrity-17', displayName: 'Фрида Кало' },
  { id: 'celebrity-18', displayName: 'Винсент Ван Гог' },
  { id: 'celebrity-19', displayName: 'Пабло Пикассо' },
  { id: 'celebrity-20', displayName: 'Нильс Бор' },
  { id: 'celebrity-21', displayName: 'Зигмунд Фрейд' },
  { id: 'celebrity-22', displayName: 'Конфуций' },
  { id: 'celebrity-23', displayName: 'Платон' },
  { id: 'celebrity-24', displayName: 'Аристотель' },
  { id: 'celebrity-25', displayName: 'Клод Моне' },
  { id: 'celebrity-26', displayName: 'Николай Коперник' },
  { id: 'celebrity-27', displayName: 'Иоганн Себастьян Бах' },
  { id: 'celebrity-28', displayName: 'Иммануил Кант' },
  { id: 'celebrity-29', displayName: 'Жан-Жак Руссо' },
  { id: 'celebrity-30', displayName: 'Карл Линней' },
  { id: 'celebrity-31', displayName: 'Майкл Фарадей' },
  { id: 'celebrity-32', displayName: 'Дмитрий Менделеев' },
  { id: 'celebrity-33', displayName: 'Пётр Чайковский' },
  { id: 'celebrity-34', displayName: 'Иоганн Гутенберг' },
  { id: 'celebrity-35', displayName: 'Марко Поло' },
  { id: 'celebrity-36', displayName: 'Рене Декарт' },
  { id: 'celebrity-37', displayName: 'Томас Эдисон' },
  { id: 'celebrity-38', displayName: 'Джеймс Уатт' },
  { id: 'celebrity-39', displayName: 'Адам Смит' },
  { id: 'celebrity-40', displayName: 'Вольтер' },
  { id: 'celebrity-41', displayName: 'Иоганн Вольфганг Гёте' },
  { id: 'celebrity-42', displayName: 'Эдгар Аллан По' },
  { id: 'celebrity-43', displayName: 'Антон Чехов' },
  { id: 'celebrity-44', displayName: 'Лев Толстой' },
  { id: 'celebrity-45', displayName: 'Фёдор Достоевский' },
  { id: 'celebrity-46', displayName: 'Иван Тургенев' },
  { id: 'celebrity-47', displayName: 'Николай Гоголь' },
  { id: 'celebrity-48', displayName: 'Михаил Ломоносов' },
  { id: 'celebrity-49', displayName: 'Генрих Шлиман' },
  { id: 'celebrity-50', displayName: 'Авраам Линкольн' },
];

const ANIMALS: Card[] = [
  { id: 'animal-01', displayName: 'Лев' },
  { id: 'animal-02', displayName: 'Тигр' },
  { id: 'animal-03', displayName: 'Слон' },
  { id: 'animal-04', displayName: 'Жираф' },
  { id: 'animal-05', displayName: 'Зебра' },
  { id: 'animal-06', displayName: 'Панда' },
  { id: 'animal-07', displayName: 'Коала' },
  { id: 'animal-08', displayName: 'Кенгуру' },
  { id: 'animal-09', displayName: 'Волк' },
  { id: 'animal-10', displayName: 'Лиса' },
  { id: 'animal-11', displayName: 'Медведь' },
  { id: 'animal-12', displayName: 'Пингвин' },
  { id: 'animal-13', displayName: 'Дельфин' },
  { id: 'animal-14', displayName: 'Акула' },
  { id: 'animal-15', displayName: 'Орёл' },
  { id: 'animal-16', displayName: 'Сова' },
  { id: 'animal-17', displayName: 'Крокодил' },
  { id: 'animal-18', displayName: 'Черепаха' },
  { id: 'animal-19', displayName: 'Хамелеон' },
  { id: 'animal-20', displayName: 'Фламинго' },
  { id: 'animal-21', displayName: 'Осьминог' },
  { id: 'animal-22', displayName: 'Бабочка' },
  { id: 'animal-23', displayName: 'Пчела' },
  { id: 'animal-24', displayName: 'Ёж' },
  { id: 'animal-25', displayName: 'Белка' },
  { id: 'animal-26', displayName: 'Гепард' },
  { id: 'animal-27', displayName: 'Леопард' },
  { id: 'animal-28', displayName: 'Носорог' },
  { id: 'animal-29', displayName: 'Бегемот' },
  { id: 'animal-30', displayName: 'Горилла' },
  { id: 'animal-31', displayName: 'Шимпанзе' },
  { id: 'animal-32', displayName: 'Ленивец' },
  { id: 'animal-33', displayName: 'Выдра' },
  { id: 'animal-34', displayName: 'Барсук' },
  { id: 'animal-35', displayName: 'Енот' },
  { id: 'animal-36', displayName: 'Олень' },
  { id: 'animal-37', displayName: 'Лось' },
  { id: 'animal-38', displayName: 'Верблюд' },
  { id: 'animal-39', displayName: 'Як' },
  { id: 'animal-40', displayName: 'Муравьед' },
  { id: 'animal-41', displayName: 'Скунс' },
  { id: 'animal-42', displayName: 'Дикобраз' },
  { id: 'animal-43', displayName: 'Тукан' },
  { id: 'animal-44', displayName: 'Попугай' },
  { id: 'animal-45', displayName: 'Павлин' },
  { id: 'animal-46', displayName: 'Пеликан' },
  { id: 'animal-47', displayName: 'Журавль' },
  { id: 'animal-48', displayName: 'Лебедь' },
  { id: 'animal-49', displayName: 'Морж' },
  { id: 'animal-50', displayName: 'Тюлень' },
];

const PROFESSIONS: Card[] = [
  { id: 'profession-01', displayName: 'Врач' },
  { id: 'profession-02', displayName: 'Учитель' },
  { id: 'profession-03', displayName: 'Пожарный' },
  { id: 'profession-04', displayName: 'Полицейский' },
  { id: 'profession-05', displayName: 'Повар' },
  { id: 'profession-06', displayName: 'Пилот' },
  { id: 'profession-07', displayName: 'Музыкант' },
  { id: 'profession-08', displayName: 'Художник' },
  { id: 'profession-09', displayName: 'Писатель' },
  { id: 'profession-10', displayName: 'Программист' },
  { id: 'profession-11', displayName: 'Строитель' },
  { id: 'profession-12', displayName: 'Фотограф' },
  { id: 'profession-13', displayName: 'Актёр' },
  { id: 'profession-14', displayName: 'Юрист' },
  { id: 'profession-15', displayName: 'Инженер' },
  { id: 'profession-16', displayName: 'Моряк' },
  { id: 'profession-17', displayName: 'Почтальон' },
  { id: 'profession-18', displayName: 'Парикмахер' },
  { id: 'profession-19', displayName: 'Садовник' },
  { id: 'profession-20', displayName: 'Ветеринар' },
  { id: 'profession-21', displayName: 'Космонавт' },
  { id: 'profession-22', displayName: 'Археолог' },
  { id: 'profession-23', displayName: 'Детектив' },
  { id: 'profession-24', displayName: 'Фермер' },
  { id: 'profession-25', displayName: 'Спортсмен' },
  { id: 'profession-26', displayName: 'Стоматолог' },
  { id: 'profession-27', displayName: 'Электрик' },
  { id: 'profession-28', displayName: 'Сантехник' },
  { id: 'profession-29', displayName: 'Таможенник' },
  { id: 'profession-30', displayName: 'Дипломат' },
  { id: 'profession-31', displayName: 'Переводчик' },
  { id: 'profession-32', displayName: 'Психолог' },
  { id: 'profession-33', displayName: 'Дизайнер' },
  { id: 'profession-34', displayName: 'Архитектор' },
  { id: 'profession-35', displayName: 'Библиотекарь' },
  { id: 'profession-36', displayName: 'Кондитер' },
  { id: 'profession-37', displayName: 'Бортпроводник' },
  { id: 'profession-38', displayName: 'Диджей' },
  { id: 'profession-39', displayName: 'Тренер' },
  { id: 'profession-40', displayName: 'Гид' },
  { id: 'profession-41', displayName: 'Пекарь' },
  { id: 'profession-42', displayName: 'Мясник' },
  { id: 'profession-43', displayName: 'Лесник' },
  { id: 'profession-44', displayName: 'Шахтёр' },
  { id: 'profession-45', displayName: 'Токарь' },
  { id: 'profession-46', displayName: 'Сварщик' },
  { id: 'profession-47', displayName: 'Крановщик' },
  { id: 'profession-48', displayName: 'Ювелир' },
  { id: 'profession-49', displayName: 'Реставратор' },
  { id: 'profession-50', displayName: 'Нотариус' },
];

// Titles only — no posters, stills, box art or logos are reproduced anywhere in this
// app. Mixes films and TV series (the deck covers both, see DECK_LABELS below).
const MOVIES: Card[] = [
  { id: 'movie-01', displayName: 'Титаник' },
  { id: 'movie-02', displayName: 'Матрица' },
  { id: 'movie-03', displayName: 'Крёстный отец' },
  { id: 'movie-04', displayName: 'Побег из Шоушенка' },
  { id: 'movie-05', displayName: 'Форрест Гамп' },
  { id: 'movie-06', displayName: 'Бойцовский клуб' },
  { id: 'movie-07', displayName: 'Интерстеллар' },
  { id: 'movie-08', displayName: 'Начало' },
  { id: 'movie-09', displayName: 'Гладиатор' },
  { id: 'movie-10', displayName: 'Король Лев' },
  { id: 'movie-11', displayName: 'Джокер' },
  { id: 'movie-12', displayName: 'Терминатор' },
  { id: 'movie-13', displayName: 'Чужой' },
  { id: 'movie-14', displayName: 'Молчание ягнят' },
  { id: 'movie-15', displayName: 'Список Шиндлера' },
  { id: 'movie-16', displayName: 'Назад в будущее' },
  { id: 'movie-17', displayName: 'Пираты Карибского моря' },
  { id: 'movie-18', displayName: 'Касабланка' },
  { id: 'movie-19', displayName: 'Иван Васильевич меняет профессию' },
  { id: 'movie-20', displayName: 'Бриллиантовая рука' },
  { id: 'movie-21', displayName: 'Операция «Ы»' },
  { id: 'movie-22', displayName: 'Ирония судьбы' },
  { id: 'movie-23', displayName: 'Москва слезам не верит' },
  { id: 'movie-24', displayName: 'Кавказская пленница' },
  { id: 'movie-25', displayName: 'Джентльмены удачи' },
  { id: 'movie-26', displayName: 'Зелёная книга' },
  { id: 'movie-27', displayName: 'Игра престолов' },
  { id: 'movie-28', displayName: 'Друзья' },
  { id: 'movie-29', displayName: 'Во все тяжкие' },
  { id: 'movie-30', displayName: 'Шерлок' },
  { id: 'movie-31', displayName: 'Властелин колец' },
  { id: 'movie-32', displayName: 'Гарри Поттер' },
  { id: 'movie-33', displayName: 'Пятый элемент' },
  { id: 'movie-34', displayName: 'Теория большого взрыва' },
  { id: 'movie-35', displayName: 'Очень странные дела' },
  { id: 'movie-36', displayName: 'Симпсоны' },
  { id: 'movie-37', displayName: 'Рик и Морти' },
  { id: 'movie-38', displayName: 'Офис' },
  { id: 'movie-39', displayName: 'Корона' },
  { id: 'movie-40', displayName: 'Чернобыль' },
  { id: 'movie-41', displayName: 'Бригада' },
  { id: 'movie-42', displayName: 'Кухня' },
  { id: 'movie-43', displayName: 'Физрук' },
  { id: 'movie-44', displayName: 'Слово пацана' },
  { id: 'movie-45', displayName: 'Ведьмак' },
  { id: 'movie-46', displayName: 'Мандалорец' },
  { id: 'movie-47', displayName: 'Пацаны' },
  { id: 'movie-48', displayName: 'Эйфория' },
  { id: 'movie-49', displayName: 'Игра в кальмара' },
  { id: 'movie-50', displayName: 'Брат' },
];

// Titles only — no box art, sprites or logos are reproduced anywhere in this app.
const VIDEO_GAMES: Card[] = [
  { id: 'game-01', displayName: 'Тетрис' },
  { id: 'game-02', displayName: 'Марио' },
  { id: 'game-03', displayName: 'Соник' },
  { id: 'game-04', displayName: 'Пакман' },
  { id: 'game-05', displayName: 'Minecraft' },
  { id: 'game-06', displayName: 'Fortnite' },
  { id: 'game-07', displayName: 'Ведьмак 3' },
  { id: 'game-08', displayName: 'Dota 2' },
  { id: 'game-09', displayName: 'Counter-Strike' },
  { id: 'game-10', displayName: 'Warcraft III' },
  { id: 'game-11', displayName: 'S.T.A.L.K.E.R.' },
  { id: 'game-12', displayName: 'Portal' },
  { id: 'game-13', displayName: 'Half-Life' },
  { id: 'game-14', displayName: 'SimCity' },
  { id: 'game-15', displayName: 'Civilization' },
  { id: 'game-16', displayName: 'Crash Bandicoot' },
  { id: 'game-17', displayName: 'Among Us' },
  { id: 'game-18', displayName: 'GTA V' },
  { id: 'game-19', displayName: 'Resident Evil' },
  { id: 'game-20', displayName: 'Elden Ring' },
  { id: 'game-21', displayName: 'Red Dead Redemption 2' },
  { id: 'game-22', displayName: 'Overwatch' },
  { id: 'game-23', displayName: 'League of Legends' },
  { id: 'game-24', displayName: 'Pokémon' },
  { id: 'game-25', displayName: 'Angry Birds' },
  { id: 'game-26', displayName: 'Doom' },
  { id: 'game-27', displayName: 'Diablo' },
  { id: 'game-28', displayName: 'StarCraft' },
  { id: 'game-29', displayName: 'Need for Speed' },
  { id: 'game-30', displayName: 'FIFA' },
  { id: 'game-31', displayName: 'Call of Duty' },
  { id: 'game-32', displayName: 'Battlefield' },
  { id: 'game-33', displayName: 'The Sims' },
  { id: 'game-34', displayName: 'Assassin’s Creed' },
  { id: 'game-35', displayName: 'Far Cry' },
  { id: 'game-36', displayName: 'Cyberpunk 2077' },
  { id: 'game-37', displayName: 'Hollow Knight' },
  { id: 'game-38', displayName: 'Celeste' },
  { id: 'game-39', displayName: 'Stardew Valley' },
  { id: 'game-40', displayName: 'Terraria' },
  { id: 'game-41', displayName: 'Subnautica' },
  { id: 'game-42', displayName: 'Dead Space' },
  { id: 'game-43', displayName: 'Silent Hill' },
  { id: 'game-44', displayName: 'Metro 2033' },
  { id: 'game-45', displayName: 'Atomic Heart' },
  { id: 'game-46', displayName: 'Brawl Stars' },
  { id: 'game-47', displayName: 'Clash Royale' },
  { id: 'game-48', displayName: 'Roblox' },
  { id: 'game-49', displayName: 'Genshin Impact' },
  { id: 'game-50', displayName: 'Hearthstone' },
];

// Currently popular, living actors/actresses — names only, same as Movies/VideoGames
// above: no photos, posters or any real likeness anywhere, just a generated illustration.
// Unlike CELEBRITIES this deliberately includes living people (that's the whole point —
// "most popular right now" can't mean historical figures), which is why it's its own
// deck instead of being folded into CELEBRITIES.
const ACTORS: Card[] = [
  { id: 'actor-01', displayName: 'Леонардо Ди Каприо' },
  { id: 'actor-02', displayName: 'Скарлетт Йоханссон' },
  { id: 'actor-03', displayName: 'Том Хэнкс' },
  { id: 'actor-04', displayName: 'Мэрил Стрип' },
  { id: 'actor-05', displayName: 'Дензел Вашингтон' },
  { id: 'actor-06', displayName: 'Эмма Уотсон' },
  { id: 'actor-07', displayName: 'Брэд Питт' },
  { id: 'actor-08', displayName: 'Анджелина Джоли' },
  { id: 'actor-09', displayName: 'Роберт Дауни младший' },
  { id: 'actor-10', displayName: 'Зендея' },
  { id: 'actor-11', displayName: 'Тимоти Шаламе' },
  { id: 'actor-12', displayName: 'Марго Робби' },
  { id: 'actor-13', displayName: 'Дуэйн Джонсон' },
  { id: 'actor-14', displayName: 'Дженнифер Лоуренс' },
  { id: 'actor-15', displayName: 'Райан Гослинг' },
  { id: 'actor-16', displayName: 'Эмма Стоун' },
  { id: 'actor-17', displayName: 'Том Холланд' },
  { id: 'actor-18', displayName: 'Флоренс Пью' },
  { id: 'actor-19', displayName: 'Киану Ривз' },
  { id: 'actor-20', displayName: 'Энн Хэтэуэй' },
  { id: 'actor-21', displayName: 'Крис Хемсворт' },
  { id: 'actor-22', displayName: 'Натали Портман' },
  { id: 'actor-23', displayName: 'Уилл Смит' },
  { id: 'actor-24', displayName: 'Шарлиз Терон' },
  { id: 'actor-25', displayName: 'Кейт Бланшетт' },
  { id: 'actor-26', displayName: 'Хью Джекман' },
  { id: 'actor-27', displayName: 'Николь Кидман' },
  { id: 'actor-28', displayName: 'Сандра Буллок' },
  { id: 'actor-29', displayName: 'Бенедикт Камбербэтч' },
  { id: 'actor-30', displayName: 'Галь Гадот' },
  { id: 'actor-31', displayName: 'Константин Хабенский' },
  { id: 'actor-32', displayName: 'Евгений Миронов' },
  { id: 'actor-33', displayName: 'Сергей Безруков' },
  { id: 'actor-34', displayName: 'Данила Козловский' },
  { id: 'actor-35', displayName: 'Александр Петров' },
  { id: 'actor-36', displayName: 'Юлия Пересильд' },
  { id: 'actor-37', displayName: 'Паулина Андреева' },
  { id: 'actor-38', displayName: 'Светлана Ходченкова' },
  { id: 'actor-39', displayName: 'Милош Бикович' },
  { id: 'actor-40', displayName: 'Чулпан Хаматова' },
  { id: 'actor-41', displayName: 'Виктория Исакова' },
  { id: 'actor-42', displayName: 'Фёдор Бондарчук' },
  { id: 'actor-43', displayName: 'Ольга Куриленко' },
  { id: 'actor-44', displayName: 'Юра Борисов' },
  { id: 'actor-45', displayName: 'Любовь Аксёнова' },
  { id: 'actor-46', displayName: 'Ирина Горбачёва' },
  { id: 'actor-47', displayName: 'Марк Эйдельштейн' },
  { id: 'actor-48', displayName: 'Аглая Тарасова' },
  { id: 'actor-49', displayName: 'Антон Шагин' },
  { id: 'actor-50', displayName: 'Никита Ефремов' },
];

// Well-known, simple dishes only — nothing obscure or multi-step fancy.
const DISHES: Card[] = [
  { id: 'dish-01', displayName: 'Борщ' },
  { id: 'dish-02', displayName: 'Пельмени' },
  { id: 'dish-03', displayName: 'Блины' },
  { id: 'dish-04', displayName: 'Шашлык' },
  { id: 'dish-05', displayName: 'Оливье' },
  { id: 'dish-06', displayName: 'Плов' },
  { id: 'dish-07', displayName: 'Пицца' },
  { id: 'dish-08', displayName: 'Паста' },
  { id: 'dish-09', displayName: 'Суши' },
  { id: 'dish-10', displayName: 'Роллы' },
  { id: 'dish-11', displayName: 'Бургер' },
  { id: 'dish-12', displayName: 'Хот-дог' },
  { id: 'dish-13', displayName: 'Шаурма' },
  { id: 'dish-14', displayName: 'Пирожки' },
  { id: 'dish-15', displayName: 'Вареники' },
  { id: 'dish-16', displayName: 'Окрошка' },
  { id: 'dish-17', displayName: 'Солянка' },
  { id: 'dish-18', displayName: 'Щи' },
  { id: 'dish-19', displayName: 'Холодец' },
  { id: 'dish-20', displayName: 'Манты' },
  { id: 'dish-21', displayName: 'Хачапури' },
  { id: 'dish-22', displayName: 'Хинкали' },
  { id: 'dish-23', displayName: 'Том Ям' },
  { id: 'dish-24', displayName: 'Рамен' },
  { id: 'dish-25', displayName: 'Карри' },
  { id: 'dish-26', displayName: 'Тако' },
  { id: 'dish-27', displayName: 'Бурито' },
  { id: 'dish-28', displayName: 'Начос' },
  { id: 'dish-29', displayName: 'Лазанья' },
  { id: 'dish-30', displayName: 'Ризотто' },
  { id: 'dish-31', displayName: 'Паэлья' },
  { id: 'dish-32', displayName: 'Фалафель' },
  { id: 'dish-33', displayName: 'Гуляш' },
  { id: 'dish-34', displayName: 'Омлет' },
  { id: 'dish-35', displayName: 'Оладьи' },
  { id: 'dish-36', displayName: 'Каша' },
  { id: 'dish-37', displayName: 'Сырники' },
  { id: 'dish-38', displayName: 'Запеканка' },
  { id: 'dish-39', displayName: 'Салат Цезарь' },
  { id: 'dish-40', displayName: 'Греческий салат' },
  { id: 'dish-41', displayName: 'Винегрет' },
  { id: 'dish-42', displayName: 'Сельдь под шубой' },
  { id: 'dish-43', displayName: 'Крем-брюле' },
  { id: 'dish-44', displayName: 'Тирамису' },
  { id: 'dish-45', displayName: 'Чизкейк' },
  { id: 'dish-46', displayName: 'Мороженое' },
  { id: 'dish-47', displayName: 'Торт «Наполеон»' },
  { id: 'dish-48', displayName: 'Жареная картошка' },
  { id: 'dish-49', displayName: 'Пюре' },
  { id: 'dish-50', displayName: 'Котлета' },
];

// Generic clothing item types — not brand names (see BRANDS below for that).
const CLOTHING: Card[] = [
  { id: 'clothing-01', displayName: 'Футболка' },
  { id: 'clothing-02', displayName: 'Джинсы' },
  { id: 'clothing-03', displayName: 'Платье' },
  { id: 'clothing-04', displayName: 'Рубашка' },
  { id: 'clothing-05', displayName: 'Куртка' },
  { id: 'clothing-06', displayName: 'Пальто' },
  { id: 'clothing-07', displayName: 'Свитер' },
  { id: 'clothing-08', displayName: 'Худи' },
  { id: 'clothing-09', displayName: 'Шорты' },
  { id: 'clothing-10', displayName: 'Юбка' },
  { id: 'clothing-11', displayName: 'Костюм' },
  { id: 'clothing-12', displayName: 'Пиджак' },
  { id: 'clothing-13', displayName: 'Жилет' },
  { id: 'clothing-14', displayName: 'Брюки' },
  { id: 'clothing-15', displayName: 'Леггинсы' },
  { id: 'clothing-16', displayName: 'Комбинезон' },
  { id: 'clothing-17', displayName: 'Пуховик' },
  { id: 'clothing-18', displayName: 'Плащ' },
  { id: 'clothing-19', displayName: 'Кардиган' },
  { id: 'clothing-20', displayName: 'Блузка' },
  { id: 'clothing-21', displayName: 'Сарафан' },
  { id: 'clothing-22', displayName: 'Шапка' },
  { id: 'clothing-23', displayName: 'Кепка' },
  { id: 'clothing-24', displayName: 'Шляпа' },
  { id: 'clothing-25', displayName: 'Берет' },
  { id: 'clothing-26', displayName: 'Шарф' },
  { id: 'clothing-27', displayName: 'Перчатки' },
  { id: 'clothing-28', displayName: 'Варежки' },
  { id: 'clothing-29', displayName: 'Носки' },
  { id: 'clothing-30', displayName: 'Колготки' },
  { id: 'clothing-31', displayName: 'Кроссовки' },
  { id: 'clothing-32', displayName: 'Туфли' },
  { id: 'clothing-33', displayName: 'Сапоги' },
  { id: 'clothing-34', displayName: 'Ботинки' },
  { id: 'clothing-35', displayName: 'Сандалии' },
  { id: 'clothing-36', displayName: 'Тапочки' },
  { id: 'clothing-37', displayName: 'Валенки' },
  { id: 'clothing-38', displayName: 'Галстук' },
  { id: 'clothing-39', displayName: 'Бабочка (галстук)' },
  { id: 'clothing-40', displayName: 'Ремень' },
  { id: 'clothing-41', displayName: 'Сумка' },
  { id: 'clothing-42', displayName: 'Рюкзак' },
  { id: 'clothing-43', displayName: 'Шапка-ушанка' },
  { id: 'clothing-44', displayName: 'Купальник' },
  { id: 'clothing-45', displayName: 'Плавки' },
  { id: 'clothing-46', displayName: 'Пижама' },
  { id: 'clothing-47', displayName: 'Халат' },
  { id: 'clothing-48', displayName: 'Фартук' },
  { id: 'clothing-49', displayName: 'Митенки' },
  { id: 'clothing-50', displayName: 'Бейсболка' },
];

// Platform names only, no logos — see mediaIcons.tsx for how that's kept generic.
// "Социальные сети" broadened a little to include well-known messengers too, or 50
// genuinely distinct, famous-enough entries wouldn't fit.
const SOCIAL_NETWORKS: Card[] = [
  { id: 'social-01', displayName: 'ВКонтакте' },
  { id: 'social-02', displayName: 'Одноклассники' },
  { id: 'social-03', displayName: 'Telegram' },
  { id: 'social-04', displayName: 'WhatsApp' },
  { id: 'social-05', displayName: 'Instagram' },
  { id: 'social-06', displayName: 'Facebook' },
  { id: 'social-07', displayName: 'Twitter (X)' },
  { id: 'social-08', displayName: 'TikTok' },
  { id: 'social-09', displayName: 'YouTube' },
  { id: 'social-10', displayName: 'Pinterest' },
  { id: 'social-11', displayName: 'Reddit' },
  { id: 'social-12', displayName: 'LinkedIn' },
  { id: 'social-13', displayName: 'Snapchat' },
  { id: 'social-14', displayName: 'Discord' },
  { id: 'social-15', displayName: 'Viber' },
  { id: 'social-16', displayName: 'Skype' },
  { id: 'social-17', displayName: 'WeChat' },
  { id: 'social-18', displayName: 'Line' },
  { id: 'social-19', displayName: 'Threads' },
  { id: 'social-20', displayName: 'Tumblr' },
  { id: 'social-21', displayName: 'Likee' },
  { id: 'social-22', displayName: 'Twitch' },
  { id: 'social-23', displayName: 'Яндекс Дзен' },
  { id: 'social-24', displayName: 'Mail.ru Агент' },
  { id: 'social-25', displayName: 'ICQ' },
  { id: 'social-26', displayName: 'Vimeo' },
  { id: 'social-27', displayName: 'Quora' },
  { id: 'social-28', displayName: 'Medium' },
  { id: 'social-29', displayName: 'Signal' },
  { id: 'social-30', displayName: 'Clubhouse' },
  { id: 'social-31', displayName: 'BeReal' },
  { id: 'social-32', displayName: 'Behance' },
  { id: 'social-33', displayName: 'Flickr' },
  { id: 'social-34', displayName: 'Myspace' },
  { id: 'social-35', displayName: 'Mastodon' },
  { id: 'social-36', displayName: 'Rutube' },
  { id: 'social-37', displayName: 'Kwai' },
  { id: 'social-38', displayName: 'Weverse' },
  { id: 'social-39', displayName: 'Patreon' },
  { id: 'social-40', displayName: 'Microsoft Teams' },
  { id: 'social-41', displayName: 'Zoom' },
  { id: 'social-42', displayName: 'Google Meet' },
  { id: 'social-43', displayName: 'Slack' },
  { id: 'social-44', displayName: 'KakaoTalk' },
  { id: 'social-45', displayName: 'Kik' },
  { id: 'social-46', displayName: 'Houseparty' },
  { id: 'social-47', displayName: 'Periscope' },
  { id: 'social-48', displayName: 'Vine' },
  { id: 'social-49', displayName: 'Google+' },
  { id: 'social-50', displayName: 'Яндекс Мессенджер' },
];

// Titles only — no stills, logos or character art reproduced anywhere in this app.
const ANIME: Card[] = [
  { id: 'anime-01', displayName: 'Наруто' },
  { id: 'anime-02', displayName: 'Блич' },
  { id: 'anime-03', displayName: 'Ван-Пис' },
  { id: 'anime-04', displayName: 'Атака титанов' },
  { id: 'anime-05', displayName: 'Токийский гуль' },
  { id: 'anime-06', displayName: 'Магическая битва' },
  { id: 'anime-07', displayName: 'Клинок, рассекающий демонов' },
  { id: 'anime-08', displayName: 'Моя геройская академия' },
  { id: 'anime-09', displayName: 'Семь смертных грехов' },
  { id: 'anime-10', displayName: 'Хвост Феи' },
  { id: 'anime-11', displayName: 'Тетрадь смерти' },
  { id: 'anime-12', displayName: 'Стальной алхимик' },
  { id: 'anime-13', displayName: 'Евангелион' },
  { id: 'anime-14', displayName: 'Код Гиас' },
  { id: 'anime-15', displayName: 'Твоё имя' },
  { id: 'anime-16', displayName: 'Унесённые призраками' },
  { id: 'anime-17', displayName: 'Принцесса Мононоке' },
  { id: 'anime-18', displayName: 'Мой сосед Тоторо' },
  { id: 'anime-19', displayName: 'Сейлор Мун' },
  { id: 'anime-20', displayName: 'Покемон' },
  { id: 'anime-21', displayName: 'Драконий жемчуг' },
  { id: 'anime-22', displayName: 'Ковбой Бибоп' },
  { id: 'anime-23', displayName: 'Гуррен-Лаганн' },
  { id: 'anime-24', displayName: 'Волейбол!!' },
  { id: 'anime-25', displayName: 'Баскетбол Куроко' },
  { id: 'anime-26', displayName: 'Девочка-волшебница Мадока' },
  { id: 'anime-27', displayName: 'Инуяша' },
  { id: 'anime-28', displayName: 'Доктор Стоун' },
  { id: 'anime-29', displayName: 'Человек-бензопила' },
  { id: 'anime-30', displayName: 'Токийские мстители' },
  { id: 'anime-31', displayName: 'Re:Zero' },
  { id: 'anime-32', displayName: 'Повелитель' },
  { id: 'anime-33', displayName: 'Этот замечательный мир!' },
  { id: 'anime-34', displayName: 'Гинтама' },
  { id: 'anime-35', displayName: 'Клэймор' },
  { id: 'anime-36', displayName: 'Берсерк' },
  { id: 'anime-37', displayName: 'Хантер х Хантер' },
  { id: 'anime-38', displayName: 'Джоджо: Невероятные приключения' },
  { id: 'anime-39', displayName: 'Школа убийц' },
  { id: 'anime-40', displayName: 'Ванпанчмен' },
  { id: 'anime-41', displayName: 'Акира' },
  { id: 'anime-42', displayName: 'Призрак в доспехах' },
  { id: 'anime-43', displayName: 'Самурай Чамплу' },
  { id: 'anime-44', displayName: 'Наруто: Боруто' },
  { id: 'anime-45', displayName: 'Пищевые войны' },
  { id: 'anime-46', displayName: 'Паразит' },
  { id: 'anime-47', displayName: 'Семья шпиона' },
  { id: 'anime-48', displayName: 'Юрий на льду' },
  { id: 'anime-49', displayName: 'Вайолет Эвергарден' },
  { id: 'anime-50', displayName: 'Форма голоса' },
];

// Brand names only — like Movies/VideoGames/SocialNetworks, never their actual logos.
// A brand's logo is specifically their trademark (unlike a generic clothing item or
// dish), so the generated icon here is always a generic category cue, not a redrawn mark.
const BRANDS: Card[] = [
  { id: 'brand-01', displayName: 'Nike' },
  { id: 'brand-02', displayName: 'Adidas' },
  { id: 'brand-03', displayName: 'Apple' },
  { id: 'brand-04', displayName: 'Samsung' },
  { id: 'brand-05', displayName: 'Coca-Cola' },
  { id: 'brand-06', displayName: 'Pepsi' },
  { id: 'brand-07', displayName: "McDonald's" },
  { id: 'brand-08', displayName: 'KFC' },
  { id: 'brand-09', displayName: 'Starbucks' },
  { id: 'brand-10', displayName: 'IKEA' },
  { id: 'brand-11', displayName: 'Zara' },
  { id: 'brand-12', displayName: 'H&M' },
  { id: 'brand-13', displayName: 'Gucci' },
  { id: 'brand-14', displayName: 'Chanel' },
  { id: 'brand-15', displayName: 'Louis Vuitton' },
  { id: 'brand-16', displayName: 'Toyota' },
  { id: 'brand-17', displayName: 'BMW' },
  { id: 'brand-18', displayName: 'Mercedes-Benz' },
  { id: 'brand-19', displayName: 'Tesla' },
  { id: 'brand-20', displayName: 'Ferrari' },
  { id: 'brand-21', displayName: 'Sony' },
  { id: 'brand-22', displayName: 'LEGO' },
  { id: 'brand-23', displayName: 'Disney' },
  { id: 'brand-24', displayName: 'Netflix' },
  { id: 'brand-25', displayName: 'Amazon' },
  { id: 'brand-26', displayName: 'Google' },
  { id: 'brand-27', displayName: 'Microsoft' },
  { id: 'brand-28', displayName: 'Intel' },
  { id: 'brand-29', displayName: 'Nvidia' },
  { id: 'brand-30', displayName: 'Xiaomi' },
  { id: 'brand-31', displayName: 'Huawei' },
  { id: 'brand-32', displayName: "L'Oréal" },
  { id: 'brand-33', displayName: 'Nivea' },
  { id: 'brand-34', displayName: 'Gillette' },
  { id: 'brand-35', displayName: 'Puma' },
  { id: 'brand-36', displayName: 'Reebok' },
  { id: 'brand-37', displayName: "Levi's" },
  { id: 'brand-38', displayName: 'Ray-Ban' },
  { id: 'brand-39', displayName: 'Rolex' },
  { id: 'brand-40', displayName: 'Red Bull' },
  { id: 'brand-41', displayName: "Lay's" },
  { id: 'brand-42', displayName: 'Haribo' },
  { id: 'brand-43', displayName: 'Oreo' },
  { id: 'brand-44', displayName: 'Nutella' },
  { id: 'brand-45', displayName: 'Barilla' },
  { id: 'brand-46', displayName: 'Nestlé' },
  { id: 'brand-47', displayName: 'Danone' },
  { id: 'brand-48', displayName: 'Kinder' },
  { id: 'brand-49', displayName: 'Colgate' },
  { id: 'brand-50', displayName: 'Pampers' },
];

export const CARD_DECKS: Record<DeckId, Card[]> = {
  [DeckId.Fictional]: FICTIONAL,
  [DeckId.Celebrities]: CELEBRITIES,
  [DeckId.Animals]: ANIMALS,
  [DeckId.Professions]: PROFESSIONS,
  [DeckId.Movies]: MOVIES,
  [DeckId.VideoGames]: VIDEO_GAMES,
  [DeckId.Actors]: ACTORS,
  [DeckId.Dishes]: DISHES,
  [DeckId.Clothing]: CLOTHING,
  [DeckId.SocialNetworks]: SOCIAL_NETWORKS,
  [DeckId.Anime]: ANIME,
  [DeckId.Brands]: BRANDS,
};

export const DECK_LABELS: Record<DeckId, string> = {
  [DeckId.Fictional]: 'Вымышленные персонажи',
  [DeckId.Celebrities]: 'Известные личности',
  [DeckId.Animals]: 'Животные',
  [DeckId.Professions]: 'Профессии',
  [DeckId.Movies]: 'Фильмы и сериалы',
  [DeckId.VideoGames]: 'Видеоигры',
  [DeckId.Actors]: 'Актёры и актрисы',
  [DeckId.Dishes]: 'Блюда',
  [DeckId.Clothing]: 'Одежда',
  [DeckId.SocialNetworks]: 'Социальные сети',
  [DeckId.Anime]: 'Аниме',
  [DeckId.Brands]: 'Известные бренды',
};

export const DEFAULT_DECK_ID = DeckId.Fictional;

/** Cards actually put on the 5×5 board per game — drawn at random out of each 50-card deck. */
export const BOARD_SIZE = 25;

export function getDeckCards(deckId: DeckId): Card[] {
  return CARD_DECKS[deckId];
}

export function isValidDeckId(value: string): value is DeckId {
  return (Object.values(DeckId) as string[]).includes(value);
}
